services:
  waveform-generator:
    build:
      context: ..
      dockerfile: waveform-reader/Dockerfile
      target: waveform_generator
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        http_proxy: ${http_proxy}
        HTTPS_PROXY: ${HTTPS_PROXY}
        https_proxy: ${https_proxy}
        SERVICE_SRC_DIR: waveform-generator
    env_file:
      - ../../config/waveform-generator-config-envs
    logging:
      driver: "json-file"
    restart: "no"
    depends_on:
      - waveform-reader
